{
 "title": "Jenkins Masters",
 "description": "Dashboard for when you are using multiple Jenkins Masters",
 "tags": [
  "Jenkins",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Master",
    "query": "label_values(jenkins_health_check_duration, app_kubernetes_io_instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jenkins_health_check_duration, kubernetes_namespace)"
   },
   {
    "name": "node",
    "label": "K8S Node",
    "query": "label_values(kube_node_info{component=\"kube-state-metrics\"}, node)"
   },
   {
    "name": "Test",
    "query": "label_values(jenkins_health_check_duration, kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Good HTTP Request Ratio",
   "type": "graph",
   "description": "The ratio of ok (200) request out of all requests.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(http_responseCodes_ok_total{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) \nby (app_kubernetes_io_instance) / \nsum(http_requests_count{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) \nby (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "description": "Http Server Errors (500)",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_responseCodes_serverError_total{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Job Wait Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (jenkins_job_waiting_duration{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Avg Build Duration Minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sum(jenkins_job_building_duration{quantile=\"0.5\",kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"})\nby (app_kubernetes_io_instance) / 60",
     "legendFormat": "p50-{{app_kubernetes_io_instance}}"
    },
    {
     "expr": "sum(jenkins_node_builds{quantile=\"0.999\",kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"})\nby (app_kubernetes_io_instance) / 60",
     "legendFormat": "p999-{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Health Check Duration (99%)",
   "type": "graph",
   "description": "How long the health check takes to complete at the 99th percentile.\nHigher numbers signify problems",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jenkins_health_check_duration{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\", quantile=\"0.99\"}) \n    by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (99%)",
   "type": "graph",
   "description": "The 99% percentile of HTTP Requests handled by Jenkins masters.",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\",quantile=\"0.99\"} ) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Ingress Perfomance",
   "type": "graph",
   "description": "Shows performance of Ingress Controller connection that lasts longer than 250 milliseconds",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(\n  nginx_ingress_controller_request_duration_seconds_bucket{\n    le=\"0.25\",\n    namespace=~\"$namespace\",\n   ingress=~\"jenkins*\"\n  }[5m]\n)) \nby (ingress) / \nsum(rate(\n  nginx_ingress_controller_request_duration_seconds_count{\n   namespace=~\"$namespace\",\n   ingress=~\"jenkins*\"\n  }[5m]\n)) \nby (ingress) ",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Number of Masters",
   "type": "singlestat",
   "description": "Amount of Masters healthy",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jenkins_health_check_score{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Health Score",
   "type": "table",
   "description": "Dropwizard based Health Score derived from other metrics",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "jenkins_health_check_score{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Job Success Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "sum(jenkins_runs_success_total{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"})\nby (app_kubernetes_io_instance) /\nsum(jenkins_runs_total_total{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"})\nby (app_kubernetes_io_instance) * 100",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Job Queue",
   "type": "graph",
   "description": "Amount of Jobs Currenty in the Queue",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jenkins_queue_size_value{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Runs Per Day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jenkins_runs_total_total{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}[24h])) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}-total"
    },
    {
     "expr": "sum(increase(jenkins_runs_failure_total{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}[24h])) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}-failed"
    },
    {
     "expr": "sum(increase(jenkins_runs_aborted_total{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}[24h])) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}-aborted"
    }
   ]
  },
  {
   "title": "Build Runs",
   "type": "graph",
   "description": "Active Build Runs",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jenkins_executor_in_use_history{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Job Runs Heatmap",
   "type": "heatmap",
   "description": "Heatmap of when Jobs are scheduled",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(jenkins_runs_total_total{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}[2h])) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Plugin Count",
   "type": "table",
   "description": "Jenkins Master Plugin Count",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "jenkins_plugins_active{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Plugin Updates Available",
   "type": "table",
   "description": "Amount of plugins that are available for updating",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 33 },
   "targets": [
    {
     "expr": "sum(jenkins_plugins_withUpdate{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "table",
   "description": "Jenkins Master Job Count",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 33 },
   "targets": [
    {
     "expr": "jenkins_job_count_value{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Offline Nodes",
   "type": "table",
   "description": "Counts offline build nodes that are connected to this master",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(jenkins_node_offline_value{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "description": "Uptime in hours",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 38 },
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"} / 3600000 ",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Master Executor Count",
   "type": "table",
   "description": "The current Master executor count, masters should not have executors, so only 0 is green.",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 38 },
   "targets": [
    {
     "expr": "sum(jenkins_executor_count_value{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "JVM GC Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(vm_gc_G1_Young_Generation_time{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"})by (app_kubernetes_io_instance) \n/ \nsum (vm_uptime_milliseconds{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Memory Ratio",
   "type": "graph",
   "description": "Ratio of JVM Memory used",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(vm_memory_heap_usage{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}) by (app_kubernetes_io_instance)",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "description": "JVM CPU Load",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_cpu_load{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "JVM Memory usage",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_memory_total_used{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request",
   "type": "graph",
   "description": "Lists memory usage of the Pod vs. Kubernetes Requests",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (label_join(container_memory_usage_bytes{\n    container_name=\"jenkins\",\n    namespace=~\"$namespace\"\n  }, \n  \"pod\", \n  \",\", \n  \"pod_name\"\n)) by (pod) / \nsum (kube_pod_container_resource_requests_memory_bytes { \n        container=\"jenkins\",\n        namespace=~\"$namespace\"\n    }\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File Descriptor Ratio",
   "type": "bargauge",
   "description": "The ratio of open file descriptors\nSee: https://support.cloudbees.com/hc/en-us/articles/204246140-Too-many-open-files",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 59 },
   "targets": [
    {
     "expr": "vm_file_descriptor_ratio{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  }
 ]
}