/* groovylint-disable-next-line CompileStatic */
pipeline {

    agent {
        label "${k8_agent}"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: "${github_creds}" , url: "${github_repo}"
            }
        }
        stage('Build') {
            steps {
                mvnBuild(skipTests: true)
            }
        }
    }

    post {
        success {
                junit allowEmptyResults: true, testResults: 'target/surefire-reports/*.xml'
            }
        }
}
