# Copyright (c) CloudBees, Inc.

apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: agent

#TODO: Replace by pull-request when it is supported
on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  REPOSITORY: cloudbees/terraform-aws-cloudbees-ci-eks-addon
  IMAGE: ooldap.debian
  VERSION: latest
  DOCKERFILE: .docker/ldap/openldap.Dockerfile

jobs:
  #TODO: Verify if the repository is created before running this job. If not, create it (including tags).
  build_and_push_images:
    steps:
    - name: Checkout code
      uses: cloudbees-io/checkout@v1

    - name: Set up GitHub registry
      uses: cloudbees-io/configure-oci-credentials@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REPOSITORY }}
        password: ${{ secrets.AWS_TF_CBCI_EKS_GITHUB_TOKEN }}

    - name: Build, tag, and push image to GitHub registry
      uses: cloudbees-io/kaniko@v1
      with:
        dockerfile: ${{ env.DOCKERFILE }}
        context: .
        destination: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.VERSION }}